<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0-android</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net8.0-windows10.0.19041.0</TargetFrameworks>
		<!-- Uncomment to also build the tizen app. You will need to install tizen by following this: https://github.com/Samsung/Tizen.NET -->
		<!-- <TargetFrameworks>$(TargetFrameworks);net8.0-tizen</TargetFrameworks> -->

		<OutputType>Exe</OutputType>
		<RootNamespace>WorldolioMauiPOC</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<!-- Versions -->
		<ApplicationDisplayVersion>0.0.27</ApplicationDisplayVersion>
		<ApplicationVersion>3</ApplicationVersion>

	    <RuntimeIdentifiers Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">android-arm;android-arm64;android-x86;android-x64</RuntimeIdentifiers>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>
		<WindowsPackageType Condition="'$(Configuration)'=='Debug'">None</WindowsPackageType>
	</PropertyGroup>
	
	<PropertyGroup Condition="'$(Configuration)'=='Debug'">
		<!-- App Identifier -->
		<ApplicationId>net.derekwilson.worldoliomauipoc.debug</ApplicationId>
		<!-- Display name -->
		<ApplicationTitle>Dbg WorldolioMauiPOC</ApplicationTitle>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)'=='Release'">
		<!-- App Identifier -->
		<ApplicationId>net.derekwilson.worldoliomauipoc</ApplicationId>
		<!-- Display name -->
		<ApplicationTitle>WorldolioMauiPOC</ApplicationTitle>
	</PropertyGroup>

	<Import Project="$(ProjectDir)..\..\..\LocalOnly\keystoreproperties.xml" Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'" />
	<Import Project="$(ProjectDir)..\..\..\LocalOnly\windowscertproperties.xml" Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows' and '$(Configuration)' == 'Release'" />

	<ItemGroup>
		<!-- App Icon -->
		<!-- Android Specific Foreground Scale -->
		<MauiIcon Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'" Include="Resources\AppIcon\appicon_worldolio.svg" ForegroundFile="Resources\AppIcon\appiconfg_worldolio.svg" Color="#00319c" ForegroundScale="0.65" />

		<!-- Default Icon Configuration for all other platforms -->
		<MauiIcon Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) != 'android'" Include="Resources\AppIcon\appicon_worldolio.svg" ForegroundFile="Resources\AppIcon\appiconfg_worldolio.svg" Color="#00319c" />

		<MauiImage Include="Resources\Icons\arrow_back.svg" />
		<MauiImage Include="Resources\Icons\globe.svg" />
		<MauiImage Include="Resources\Icons\info.svg" />
		<MauiImage Include="Resources\Icons\moon.svg" />
		<MauiImage Include="Resources\Icons\plan.svg" />
		<MauiImage Include="Resources\Icons\settings.svg" />

		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\Splash\splash_worldolio.svg" Color="#00319c" BaseSize="128,128" />

		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />
		<MauiImage Update="Resources\Images\dotnet_bot.png" Resize="True" BaseSize="300,185" />

		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="nlog.config" />
	  <None Remove="Resources\Icons\arrow_back.svg" />
	  <None Remove="Resources\Icons\globe.svg" />
	  <None Remove="Resources\Icons\info.svg" />
	  <None Remove="Resources\Icons\moon.svg" />
	  <None Remove="Resources\Icons\plan.svg" />
	  <None Remove="Resources\Icons\settings.svg" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="nlog.config" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Maui" Version="9.1.1" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
		<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="$(MauiVersion)" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="8.0.1" />
		<PackageReference Include="NLog.Extensions.Logging" Version="6.1.3" />
		<PackageReference Include="NLog.Targets.MauiLog" Version="8.6.2" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\Assemblies\Worldolio.Data\Worldolio.Data.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <MauiAsset Update="Resources\Raw\worldolio.sqlite">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </MauiAsset>
	</ItemGroup>

	<ItemGroup>
	  <MauiXaml Update="Views\About.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\CityGrid.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\CityList.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Moon.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Partial\TabBar.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Plan.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Settings.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	</ItemGroup>

	<!-- get the current git hash for use in code -->
	<Target Name="GetGitHash" BeforeTargets="BeforeBuild">
		<Exec Command="git rev-parse --short HEAD" ConsoleToMSBuild="true" StandardOutputImportance="Low">
			<Output TaskParameter="ConsoleOutput" PropertyName="GitCommitHash" />
		</Exec>

		<!-- Fallback if git is not available -->
		<PropertyGroup>
			<GitCommitHash Condition="'$(GitCommitHash)' == ''">UNKNOWN</GitCommitHash>
		</PropertyGroup>

		<!-- Write the hash into a temporary C# file compiled with the app -->
		<WriteLinesToFile
			File="$(IntermediateOutputPath)GitInfo.g.cs"
			Lines="namespace WorldolioMauiPOC { public static class GitInfo { public const string Hash = &quot;$(GitCommitHash)&quot; %3b}}"
			Overwrite="true"
			Encoding="UTF-8" />

		<ItemGroup>
			<Compile Include="$(IntermediateOutputPath)GitInfo.g.cs" />
		</ItemGroup>
	</Target>
</Project>
